#!/bin/sh
# Auto-update apphosting.yaml URL based on branch

BRANCH=$(git rev-parse --abbrev-ref HEAD)

if [ "$BRANCH" = "master" ]; then
  sed -i '' 's|value: https://unitswap.xyz|value: https://swapunits.com|g' apphosting.yaml
elif [ "$BRANCH" = "dev" ]; then
  sed -i '' 's|value: https://swapunits.com|value: https://unitswap.xyz|g' apphosting.yaml
fi
